name: APIHolders
version: ${project.version}
author: "StreackMC Team"
description: ${project.description}
website: https://github.com/StreackMC/APIHolders
api-version: '1.14'
main: com.github.streackmc.APIHolders.plugin
depend: ["StreackLib", "PlaceholderAPI"]

commands:
  apiholders:
    description: "管理 APIHolders 插件"
    usage: "/<command> <version|reload>"
    permission: apiholders.command

permissions:
  apiholders.command:
    description: "允许使用 /apiholders 管理命令"
    default: op